### ISSUE TITLE
data preprocessing

### ISSUE THREAD

**Issue by sunkaiyue0** [uncbiag/LiftReg#1]
hello，I am trying to reproduce your project, but the drr generator is missing file extract_ROI_from_syn_projection.py, would you like to share it?

**Comment by lintian-a** [comment]
Hi Sunkaiyue,

The code used to generate ROI is an experimental function that has been accidentally committed to the codebase. I removed it from the repo at [this commit](https://github.com/uncbiag/LiftReg/commit/1ac3754a23ffbc9970d2d1b7182a949cfebf3ca0). The latest code should be working.

The process to generate the testing data is to run the following two commands:
python tools/preprocessing.py -o [PATH_TO_OUTPUT_FOLDER] -d [DATASET_NAME_OF_YOUR_CHOICE] --data_type val
python tools/preprocessingDRR.py --data_path [PATH_TO_OUTPUT_FOLDER]/[DATASET_NAME_OF_YOUR_CHOICE] --drr_folder_name [DRR_FOLDER_OF_YOUR_CHOICE]  -g 0

Let me know if you have other questions.
